{% set name = "xmovie" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmovie-{{ version }}.tar.gz
  sha256: f149f1a38a5c985e4801773129e4a07c33703039f1b25fde76a8a636e9a05220

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - cartopy
    - dask-core
    - numpy
    - python >=3.6
    - xarray

test:
  imports:
    - xmovie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jbusecke/xmovie
  summary: Simply create beautiful movies from xarray objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbusecke
